
AllCops:
  NewCops: enable
Metrics/AbcSize:
  Exclude:
    - 'solutions/**/*'
Metrics/BlockLength:
  Exclude:
    - 'solutions/**/*'
Metrics/MethodLength:
  Exclude:
    - 'solutions/**/*'
Layout/LineLength:
  Max: 125
